@startuml
left to right direction
class Board {
    - boardLength: double
    - interactionRadius: double
    - boundaryCondition: BoundaryCondition
    - boardParticles: Collection<Particle>


}


enum BoundaryCondition {
    Periodic
    NotPeriodic
}



class BoardSequence {
    - board: Board
    + writeToFile(filename: String)
    - Board getNextBoard()
}


BoardSequence *- Board
Board *- BoundaryCondition


@enduml
